version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag jb-image:$CIRCLE_SHA1
      - run: git clone https://github.com/openai/jukebox.git
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag jb-image:$CIRCLE_SHA1 jukebox-docker:$CIRCLE_SHA1
          docker push jukebox-docker:$CIRCLE_SHA1


workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              only: master
