version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: git clone https://github.com/openai/jukebox.git
      - run: docker build --tag jb-image:$CIRCLE_SHA1 .
      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag jb-image:$CIRCLE_SHA1 btrude/jukebox-docker:$CIRCLE_SHA1
          docker push btrude/jukebox-docker:$CIRCLE_SHA1


workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              only: master
